name: Testes Automatizados

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Instalar dependências
        run: composer install

      - name: Executar testes
        run: ./vendor/bin/codecept run acceptance --html

      - name: Enviar screenshots em caso de falhas
        uses: actions/upload-artifact@v2
        with:
          name: Screenshots
          path: tests/_output

